# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Core'
on: push
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["splitkb_aurora_corne_left","splitkb_aurora_corne_right"]'
      alphas: '["Colemak"]'
      nav: '["default"]'
      clipboard: '["Mac"]'
      layers: '["default"]'
      mapping: '["default"]'
      custom_config: '["default"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y", "CONFIG_ZMK_SLEEP=y", "CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000", "CONFIG_BT_CTLR_TX_PWR_PLUS_8=y", "CONFIG_ZMK_KEYBOARD_NAME=\"Corne Nano\""]'
      branches: '["zmkfirmware/zmk/main ftc/zmk/mouse-ftc"]'




#
#  # Set deep sleep to 30 minutes
#  CONFIG_ZMK_SLEEP=y
#  CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000
#
#  # Make Bluetooth stronger
#  CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
#
#  # Change board name
#  CONFIG_ZMK_KEYBOARD_NAME="Corne Nano"